---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: barisozdag/workflows/.github/workflows/addon-deploy.yaml@main
    secrets:
      CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
      ADDON_TOKEN: ${{ secrets.GITHUB_TOKEN }}
