---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: barisozdag/workflows/.github/workflows/labels.yaml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
